include: package:lints/core.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unused_element: error
    unused_import: error
    unused_local_variable: error
    dead_code: error
