name: http2
version: 0.0.1
description: A HTTP/2 implementation in dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/http2

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  unittest: '>=0.11.5 <0.12.0'

